apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: adservice
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - jelly-node




#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: adservice
#       spec:
#         template:
#           metadata:
#             labels:
#               app.jellycloud.io/name: adservice
#           spec:
#             nodeSelector:
#               type: jelly-node
#             tolerations:
#               - key: virtual-kubelet.io/provider
#                 operator: "Equal"
#                 value: "jellycloud"
#                 effect: NoSchedule
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: adservice
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: adservice

#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: cartservice
#       spec:
#         template:
#           metadata:
#             labels:
#               app.jellycloud.io/name: cartservice
#           spec:
#             nodeSelector:
#               type: jelly-node
#             tolerations:
#               - key: virtual-kubelet.io/provider
#                 operator: "Equal"
#                 value: "jellycloud"
#                 effect: NoSchedule
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: cartservice
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: cartservice

#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: redis-cart
#       spec:
#         template:
#           metadata:
#             labels:
#               app.jellycloud.io/name: redis-cart
#           spec:
#             nodeSelector:
#               type: jelly-node
#             tolerations:
#               - key: virtual-kubelet.io/provider
#                 operator: "Equal"
#                 value: "jellycloud"
#                 effect: NoSchedule
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: redis-cart
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: redis-cart


#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: checkoutservice
#       spec:
#         template:
#           metadata:
#             labels:
#               app.jellycloud.io/name: checkoutservice
#           spec:
#             nodeSelector:
#               type: jelly-node
#             tolerations:
#               - key: virtual-kubelet.io/provider
#                 operator: "Equal"
#                 value: "jellycloud"
#                 effect: NoSchedule
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: checkoutservice
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: checkoutservice

#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: currencyservice
#       spec:
#         template:
#           metadata:
#             labels:
#               app.jellycloud.io/name: currencyservice
#           spec:
#             nodeSelector:
#               type: jelly-node
#             tolerations:
#               - key: virtual-kubelet.io/provider
#                 operator: "Equal"
#                 value: "jellycloud"
#                 effect: NoSchedule
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: currencyservice
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: currencyservice

#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: emailservice
#       spec:
#         template:
#           metadata:
#             labels:
#               app.jellycloud.io/name: emailservice
#           spec:
#             nodeSelector:
#               type: jelly-node
#             tolerations:
#               - key: virtual-kubelet.io/provider
#                 operator: "Equal"
#                 value: "jellycloud"
#                 effect: NoSchedule
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: emailservice
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: emailservice

#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: frontend
#       spec:
#         template:
#           metadata:
#             labels:
#               app.jellycloud.io/name: frontend
#           spec:
#             nodeSelector:
#               type: jelly-node
#             tolerations:
#               - key: virtual-kubelet.io/provider
#                 operator: "Equal"
#                 value: "jellycloud"
#                 effect: NoSchedule
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: frontend
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: frontend
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: frontend-external
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: frontend

# #  - patch: |-
# #      apiVersion: apps/v1
# #      kind: Deployment
# #      metadata:
# #        name: loadgenerator
# #      spec:
# #        template:
# #          metadata:
# #            labels:
# #              app.jellycloud.io/name: loadgenerator
# #          spec:
# #            nodeSelector:
# #              type: jelly-node
# #            tolerations:
# #              - key: virtual-kubelet.io/provider
# #                operator: "Equal"
# #                value: "jellycloud"
# #                effect: NoSchedule

#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: paymentservice
#       spec:
#         template:
#           metadata:
#             labels:
#               app.jellycloud.io/name: paymentservice
#           spec:
#             nodeSelector:
#               type: jelly-node
#             tolerations:
#               - key: virtual-kubelet.io/provider
#                 operator: "Equal"
#                 value: "jellycloud"
#                 effect: NoSchedule
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: paymentservice
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: paymentservice

#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: productcatalogservice
#       spec:
#         template:
#           metadata:
#             labels:
#               app.jellycloud.io/name: productcatalogservice
#           spec:
#             nodeSelector:
#               type: jelly-node
#             tolerations:
#               - key: virtual-kubelet.io/provider
#                 operator: "Equal"
#                 value: "jellycloud"
#                 effect: NoSchedule
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: productcatalogservice
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: productcatalogservice

#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: recommendationservice
#       spec:
#         template:
#           metadata:
#             labels:
#               app.jellycloud.io/name: recommendationservice
#           spec:
#             nodeSelector:
#               type: jelly-node
#             tolerations:
#               - key: virtual-kubelet.io/provider
#                 operator: "Equal"
#                 value: "jellycloud"
#                 effect: NoSchedule
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: recommendationservice
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: recommendationservice

#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: shippingservice
#       spec:
#         template:
#           metadata:
#             labels:
#               app.jellycloud.io/name: shippingservice
#           spec:
#             nodeSelector:
#               type: jelly-node
#             tolerations:
#               - key: virtual-kubelet.io/provider
#                 operator: "Equal"
#                 value: "jellycloud"
#                 effect: NoSchedule
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: shippingservice
#       spec:
#         selector:
#           app: null
#           app.jellycloud.io/name: shippingservice
